/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.CustomProtocol.PlayerConnectReq', null, global);
goog.exportSymbol('proto.CustomProtocol.PlayerConnectRsp', null, global);
goog.exportSymbol('proto.CustomProtocol.PlayerFrame', null, global);
goog.exportSymbol('proto.CustomProtocol.Vec3', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CustomProtocol.PlayerConnectReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CustomProtocol.PlayerConnectReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CustomProtocol.PlayerConnectReq.displayName = 'proto.CustomProtocol.PlayerConnectReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CustomProtocol.PlayerConnectReq.prototype.toObject = function(opt_includeInstance) {
  return proto.CustomProtocol.PlayerConnectReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CustomProtocol.PlayerConnectReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerConnectReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    playname: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CustomProtocol.PlayerConnectReq}
 */
proto.CustomProtocol.PlayerConnectReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CustomProtocol.PlayerConnectReq;
  return proto.CustomProtocol.PlayerConnectReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CustomProtocol.PlayerConnectReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CustomProtocol.PlayerConnectReq}
 */
proto.CustomProtocol.PlayerConnectReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CustomProtocol.PlayerConnectReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CustomProtocol.PlayerConnectReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CustomProtocol.PlayerConnectReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerConnectReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * required string playName = 1;
 * @return {string}
 */
proto.CustomProtocol.PlayerConnectReq.prototype.getPlayname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.CustomProtocol.PlayerConnectReq.prototype.setPlayname = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.CustomProtocol.PlayerConnectReq.prototype.clearPlayname = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerConnectReq.prototype.hasPlayname = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CustomProtocol.PlayerConnectRsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CustomProtocol.PlayerConnectRsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CustomProtocol.PlayerConnectRsp.displayName = 'proto.CustomProtocol.PlayerConnectRsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.toObject = function(opt_includeInstance) {
  return proto.CustomProtocol.PlayerConnectRsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CustomProtocol.PlayerConnectRsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerConnectRsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    playid: jspb.Message.getField(msg, 1),
    udpport: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CustomProtocol.PlayerConnectRsp}
 */
proto.CustomProtocol.PlayerConnectRsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CustomProtocol.PlayerConnectRsp;
  return proto.CustomProtocol.PlayerConnectRsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CustomProtocol.PlayerConnectRsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CustomProtocol.PlayerConnectRsp}
 */
proto.CustomProtocol.PlayerConnectRsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUdpport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CustomProtocol.PlayerConnectRsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CustomProtocol.PlayerConnectRsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerConnectRsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * required int32 playId = 1;
 * @return {number}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.getPlayid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.CustomProtocol.PlayerConnectRsp.prototype.setPlayid = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.CustomProtocol.PlayerConnectRsp.prototype.clearPlayid = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.hasPlayid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 udpPort = 2;
 * @return {number}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.getUdpport = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.CustomProtocol.PlayerConnectRsp.prototype.setUdpport = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.CustomProtocol.PlayerConnectRsp.prototype.clearUdpport = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerConnectRsp.prototype.hasUdpport = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CustomProtocol.Vec3 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CustomProtocol.Vec3, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CustomProtocol.Vec3.displayName = 'proto.CustomProtocol.Vec3';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CustomProtocol.Vec3.prototype.toObject = function(opt_includeInstance) {
  return proto.CustomProtocol.Vec3.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CustomProtocol.Vec3} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.Vec3.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getField(msg, 1),
    y: jspb.Message.getField(msg, 2),
    z: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CustomProtocol.Vec3}
 */
proto.CustomProtocol.Vec3.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CustomProtocol.Vec3;
  return proto.CustomProtocol.Vec3.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CustomProtocol.Vec3} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CustomProtocol.Vec3}
 */
proto.CustomProtocol.Vec3.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CustomProtocol.Vec3.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CustomProtocol.Vec3.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CustomProtocol.Vec3} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.Vec3.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * required int32 x = 1;
 * @return {number}
 */
proto.CustomProtocol.Vec3.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.CustomProtocol.Vec3.prototype.setX = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.CustomProtocol.Vec3.prototype.clearX = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.Vec3.prototype.hasX = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 y = 2;
 * @return {number}
 */
proto.CustomProtocol.Vec3.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.CustomProtocol.Vec3.prototype.setY = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.CustomProtocol.Vec3.prototype.clearY = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.Vec3.prototype.hasY = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 z = 3;
 * @return {number}
 */
proto.CustomProtocol.Vec3.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.CustomProtocol.Vec3.prototype.setZ = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.CustomProtocol.Vec3.prototype.clearZ = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.Vec3.prototype.hasZ = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CustomProtocol.PlayerFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CustomProtocol.PlayerFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CustomProtocol.PlayerFrame.displayName = 'proto.CustomProtocol.PlayerFrame';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CustomProtocol.PlayerFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.CustomProtocol.PlayerFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CustomProtocol.PlayerFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    tick: jspb.Message.getField(msg, 1),
    pos: (f = msg.getPos()) && proto.CustomProtocol.Vec3.toObject(includeInstance, f),
    playerid: jspb.Message.getField(msg, 3)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CustomProtocol.PlayerFrame}
 */
proto.CustomProtocol.PlayerFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CustomProtocol.PlayerFrame;
  return proto.CustomProtocol.PlayerFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CustomProtocol.PlayerFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CustomProtocol.PlayerFrame}
 */
proto.CustomProtocol.PlayerFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTick(value);
      break;
    case 2:
      var value = new proto.CustomProtocol.Vec3;
      reader.readMessage(value,proto.CustomProtocol.Vec3.deserializeBinaryFromReader);
      msg.setPos(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPlayerid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CustomProtocol.PlayerFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CustomProtocol.PlayerFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CustomProtocol.PlayerFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomProtocol.PlayerFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPos();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.CustomProtocol.Vec3.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * required int32 Tick = 1;
 * @return {number}
 */
proto.CustomProtocol.PlayerFrame.prototype.getTick = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.CustomProtocol.PlayerFrame.prototype.setTick = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.CustomProtocol.PlayerFrame.prototype.clearTick = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerFrame.prototype.hasTick = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required Vec3 Pos = 2;
 * @return {!proto.CustomProtocol.Vec3}
 */
proto.CustomProtocol.PlayerFrame.prototype.getPos = function() {
  return /** @type{!proto.CustomProtocol.Vec3} */ (
    jspb.Message.getWrapperField(this, proto.CustomProtocol.Vec3, 2, 1));
};


/** @param {!proto.CustomProtocol.Vec3} value */
proto.CustomProtocol.PlayerFrame.prototype.setPos = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.CustomProtocol.PlayerFrame.prototype.clearPos = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerFrame.prototype.hasPos = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 PlayerId = 3;
 * @return {number}
 */
proto.CustomProtocol.PlayerFrame.prototype.getPlayerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.CustomProtocol.PlayerFrame.prototype.setPlayerid = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.CustomProtocol.PlayerFrame.prototype.clearPlayerid = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.CustomProtocol.PlayerFrame.prototype.hasPlayerid = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.CustomProtocol);
